apiVersion: apps/v1
kind: Deployment
metadata:
  name: guinea-pig-service
  namespace: unger
spec:
  replicas: 1
  progressDeadlineSeconds: 1200
  selector:
    matchLabels:
      app: guinea-pig-service
  template:
    metadata:
      labels:
        app: guinea-pig-service
    spec:
      hostNetwork: false
      terminationGracePeriodSeconds: 86400 # 24 hours
      containers:
      - name: guinea-pig-service
        image: localhost:5000/guinea-pig-service
        imagePullPolicy: Always
        env:
        envFrom:
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 90
          timeoutSeconds: 30
          failureThreshold: 1
        lifecycle:
          preStop:
            httpGet:
              path: /prestop
              port: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: guinea-pig-service
  namespace: unger
  annotations:
spec:
  selector:
    app: guinea-pig-service
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8080
  type: LoadBalancer
